### PR TITLE
Added some more output to normal SPR test.

### PR DESCRIPTION
**Pull request by jpd002**
Added some more output to normal SPR test to inspect some of the registers values.

On a side note, it seems really strange how the PS2 handles fromSPR and toSPR transfers with MADR that has its high bit on. Looks like the high bit of MADR isn't changed when it's set but it still doesn't transfer anything to/from RAM.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Right, that's why I'd tested that bit.  It definitely seems strange.  I'm not sure if the behavior is important.

The only thing here is that you're usually looking at a diff of which lines changed.  Seeing this:

-SADR After: 00000030
+SADR After: 00000010

Might make the problem obvious, or it might not really.  I usually try to keep the lines a bit more descriptive so it's easy to tell when looking at the diff between actual and expected output what part is failing.

In the new expected file, there's a lot of space here for example, where a diff would not be very descriptive:
https://github.com/jpd002/ps2autotests/blob/normal_moreoutput/tests/dma/spr/normal.expected#L24

It may make sense to compress it down too, like `SADR %08x -> %08x`.

-[Unknown]

**Comment by jpd002** [comment]
Alright, I've changed the output to be more informative when comparing lines. Just tell me if there's anything else I can do to improve the output.

**Comment by unknownbrackets** [comment]
Thanks, sorry if it seems a bit pedantic, just want to make sure the lines are close enough.

When you've got certain tests failing and looking at it via CI, it just helps to make things as clear as possible.

I didn't even realize SADR increased, although it makes sense.  I wonder if it's worth checking MADR too?

-[Unknown]

**Comment by jpd002** [comment]
Makes sense to have diffs that give as much information as possible without having to peek inside the actual files. I still don't have a way to display diffs on my CI setup, but I totally understand the need for them to be insightful.

I guess we could print MADR, but I don't know if the addresses would be predictable. On the EE, I think it wouldn't be a problem because the BIOS doesn't manage the heap, but on the IOP, I think it would be trickier.

**Pull request merged**
